# default configuration
baseURL = "https://www.olenaspektor.com"
languageCode = "en-us"
summaryLength = "10"
theme = "espekdigital"
title = "Olena Spektor | UI/UX designer in Tauranga, New Zealand"

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# js plugin
[[params.plugins.js]]
link = "plugins/heroAnimation/perlin.js"
[[params.plugins.js]]
link = "plugins/heroAnimation/three.min.js"
[[params.plugins.js]]
link = "plugins/heroAnimation/TweenMax.min.js"
[[params.plugins.js]]
link = "plugins/heroAnimation/animation.js"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

# menu
#[[menu.main]]
#URL = "about"
#name = "About"
#weight = 1

#[[menu.main]]
#URL = "blog"
#name = "Blog"
#weight = 2

[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 3

[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4


# default parameters
[params]
home = "Home"
logo = ""
# theme color
theme_color = "#41228e"
# contact info
phone = "+64 22 0193344"
phoneTitle = "022 0193329"
email = "spektor.helen@gmail.com"
address = "2 Boyle Mews, Papamoa 3118, Bay Of Plenty, New Zealand"
# meta description
author = "Olena Spektor | UI/UX designer in Tauranga"
description = "Quality UI/UX and Graphic Designer in Tauranga. Are you looking to refresh your website design or create a mobile app? Get Your Free Quote Today. Contact Olena Spektor for UX/UI and Graphic Design work in Tauranga, New Zealand."
# google analytics
google_analytics_id = "" # Your ID
# copyright
copyright = "Copyright &copy; 2020 a theme by [gethugothemes](https://gethugothemes.com)"


# preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use png, jpg, svg or gif format

# contact
[params.contact]
enable = true
form_action = "#" # contact form works with : https://formspree.io

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

# cookies
[params.cookies]
enable = true
expire_days = 2

# social site
[[params.social]]
icon = "ti-facebook"
URL = "https://www.facebook.com/profile.php?id=100008905320721"

[[params.social]]
icon = "ti-instagram"
URL = "https://www.instagram.com/the_five_percent_/"

[[params.social]]
icon = "ti-dribbble"
URL = "https://www.behance.net/spektorhel775e"

# footer
[[params.footer.col1]]
title = "Graphic designer in Tauranga"
URL = "blog/graphic-designer-tauranga"

[[params.footer.col1]]
title = "Graphic designer in Auckland"
URL = "blog/graphic-designer-tauranga"

[[params.footer.col1]]
title = "Graphic designer in Wellington"
URL = "blog/graphic-designer-tauranga"

[[params.footer.col2]]
title = "Download my CV"
URL = "blog/graphic-designer-tauranga"

[[params.footer.col2]]
title = "Download my PDF portfolio"
URL = "blog/graphic-designer-tauranga"