backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/images
public_folder: static/images
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    format: 'frontmatter'
    fields:
      - { label: 'Title', name: 'title', widget: 'string'}
      - { label: 'Description', name: 'description', widget: 'markdown'}
      - { label: 'Date', name: 'date', widget: 'date', required: false}
      - { label: 'Image', name: 'image', widget: 'image', required: false}
      - { label: 'Body', name: 'body', widget: 'markdown', required: false}
  - name: 'about'
    label: 'About'
    folder: 'content/about'
    format: 'frontmatter'
    fields:
      - { label: 'Title', name: 'title', widget: 'string'}
      - { label: 'Description', name: 'description', widget: 'markdown'}
      - { label: 'Author Image', name: 'author_image', widget: 'image'}
      - { label: 'Author Signature', name: 'author_signature', widget: 'image'}
      - { label: 'Body', name: 'body', widget: 'markdown'}
  - name: 'contact'
    label: 'Contact'
    folder: 'content/contact'
    format: 'frontmatter'
    fields:
      - { label: 'Title', name: 'title', widget: 'string'}
      - { label: 'Description', name: 'description', widget: 'markdown'}
  - name: 'portfolio'
    label: 'Portfolio'
    folder: 'content/portfolio'
    format: 'frontmatter'
    fields:
      - { label: 'Title', name: 'title', widget: 'string'}
      - { label: 'Description', name: 'description', widget: 'markdown'}
      - { label: 'Date', name: 'date', widget: 'date', required: false}      
      - { label: 'Image', name: 'image', widget: 'image', required: false}
      - { label: 'Client name', name: 'client', widget: 'string', required: false}
      - { label: 'Project Url', name: 'project_url', widget: 'string', required: false}
      - { label: 'Categories', name: 'categories', widget: 'list', required: false}
      - { label: 'Body', name: 'body', widget: 'list', required: false}
  - label: 'Data'
    name: 'data'
    files:
      - label: "About"
        name: "about"
        file: "data/about.yml"
        fields:
          - label: 'Work Process'
            name: 'work_process'
            widget: 'object'
            fields:
              - {label: 'Title', name: 'title', widget: 'string'}
      - label: "Homepage"
        name: "homepage"
        file: "data/homepage.yml"
        fields:
          - label: 'Banner'
            name: 'banner'
            widget: 'object'
            fields:
              - {label: 'Title', name: 'title', widget: 'markdown'}