backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/images
public_folder: images
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    format: 'frontmatter'
    fields:
      - { label: 'Title', name: 'title', widget: 'string'}
      - { label: 'Description', name: 'description', widget: 'markdown'}
      - { label: 'Date', name: 'date', widget: 'date', required: false}
      - { label: 'Image', name: 'image', widget: 'image', required: false}
      - { label: 'Body', name: 'body', widget: 'markdown', required: false}
  - name: 'about'
    label: 'About'
    folder: 'content/about'
    format: 'frontmatter'
    fields:
      - { label: 'Title', name: 'title', widget: 'string'}
      - { label: 'Description', name: 'description', widget: 'markdown'}
      - { label: 'Author Image', name: 'author_image', widget: 'image'}
      - { label: 'Author Signature', name: 'author_signature', widget: 'image'}
      - { label: 'Body', name: 'body', widget: 'markdown'}
  - name: 'contact'
    label: 'Contact'
    folder: 'content/contact'
    format: 'frontmatter'
    fields:
      - { label: 'Title', name: 'title', widget: 'string'}
      - { label: 'Description', name: 'description', widget: 'markdown'}
  - name: 'portfolio'
    label: 'Portfolio'
    folder: 'content/portfolio'
    format: 'frontmatter'
    fields:
      - { label: 'Title', name: 'title', widget: 'string'}
      - { label: 'Description', name: 'description', widget: 'markdown'}
      - { label: 'Date', name: 'date', widget: 'date', required: false}      
      - { label: 'Image', name: 'image', widget: 'image', required: false}
      - { label: 'Client name', name: 'client', widget: 'string', required: false}
      - { label: 'Project Url', name: 'project_url', widget: 'string', required: false}
      - { label: 'Categories', name: 'categories', widget: 'list', required: false}
      - { label: 'Body', name: 'body', widget: 'markdown', required: false}
  - label: 'Data'
    name: 'data'
    files:      
      - label: "Homepage"
        name: "homepage"
        file: "data/homepage.yml"
        fields:
          - label: 'Banner'
            name: 'banner'
            widget: 'object'
            fields:
              - {label: 'Title', name: 'title', widget: 'markdown'}
          - label: 'About'
            name: 'about'
            widget: 'object'
            fields:
              - {label: 'Enabled', name: 'enable', widget: 'boolean'}
              - {label: 'Content', name: 'content', widget: 'markdown'}
              - label: 'Button'
                name: 'button'
                widget: 'object'
                fields:
                  - {label: 'Enable', name: 'enable', widget: 'boolean'}
                  - {label: 'Label', name: 'label', widget: 'string'}
                  - {label: 'Url', name: 'URL', widget: 'string'}
          - label: 'Service'
            name: 'service'
            widget: 'object'
            fields:
              - {label: 'Title', name: 'title', widget: 'string'}
              - {label: 'Enabled', name: 'enable', widget: 'boolean'}
              - label: 'Items'
                name: 'item'
                widget: 'list'
                fields:
                  - {label: 'Title', name: 'title', widget: 'string'}
                  - {label: 'Icon', name: 'icon', widget: 'string'}
                  - {label: 'Content', name: 'content', widget: 'markdown'}
                  - {label: 'Highlighted', name: 'highlighted', widget: 'boolean'}
          - label: 'Education'
            name: 'education'
            widget: 'object'
            fields:
              - {label: 'Title', name: 'title', widget: 'string'}
              - {label: 'Enabled', name: 'enable', widget: 'boolean'}
              - label: 'Items'
                name: 'item'
                widget: 'list'
                fields:
                  - {label: 'Title', name: 'title', widget: 'string'}
                  - {label: 'Year', name: 'year', widget: 'number'}
                  - {label: 'Academy', name: 'academy', widget: 'string'}                            
          - label: 'Portfolio'
            name: 'portfolio'
            widget: 'object'
            fields:
              - {label: 'Title', name: 'title', widget: 'string'}
              - {label: 'Enabled', name: 'enable', widget: 'boolean'}
              - {label: 'Items Count', name: 'item_show', widget: 'number'}              
          - label: 'Testimonial'
            name: 'testimonial'
            widget: 'object'
            fields:
              - {label: 'Title', name: 'title', widget: 'string'}
              - {label: 'Enabled', name: 'enable', widget: 'boolean'}
              - label: 'Items'
                name: 'item'
                widget: 'list'
                fields:
                  - {label: 'Name', name: 'name', widget: 'string'}
                  - {label: 'Image', name: 'image', widget: 'image'}
                  - {label: 'Designation', name: 'designation', widget: 'string'}
                  - {label: 'Content', name: 'content', widget: 'markdown'}
                  