backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/images
public_folder: static/images
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    fields:
      - { label: 'Title', name: 'title', widget:'string'}
      - { label: 'Description', name: 'description', widget:'markdown'}
  - name: 'about'
    label: 'About'
    folder: 'content/about'
    fields:
      - { label: 'Title', name: 'title', widget:'string'}
      - { label: 'Description', name: 'description', widget:'markdown'}
  - name: 'contact'
    label: 'Contact'
    folder: 'content/contact'
    fields:
      - { label: 'Title', name: 'title', widget:'string'}
      - { label: 'Description', name: 'description', widget:'markdown'}
  - name: 'portfolio'
    label: 'Portfolio'
    folder: 'content/portfolio'
    fields:
      - { label: 'Title', name: 'title', widget:'string'}
      - { label: 'Description', name: 'description', widget:'markdown'}
  - name: 'data'
    label: 'Data'
    folder: 'data'
    files:
      - file: "/data/about.yml"
      - file: "/data/homepage.yml"